if(EXISTS "/Users/lisaburton/Documents/code/isometric-sdl-demo/RoversRevengeTests_tests-b12d07c.cmake")
  include("/Users/lisaburton/Documents/code/isometric-sdl-demo/RoversRevengeTests_tests-b12d07c.cmake")
else()
  add_test(RoversRevengeTests_NOT_BUILT-b12d07c RoversRevengeTests_NOT_BUILT-b12d07c)
endif()
